version: '3.8'

services:
  revanced-helper:
    container_name: revanced-helper
    image: ghcr.io/revanced/revanced-helper:latest
    # Required because otherwise failing with ECONNREFUSED
    network_mode: "host"
    environment:
      - WIT_AI_TOKEN=YOUR_WIT_AI_TOKEN
      - MONGODB_URI=YOUR_MONGODB_URI
      - DISCORD_TOKEN=YOUR_DISCORD_TOKEN
    volumes:
      - /data/revanced-helper/discord-bot-config.json:/usr/src/revanced-helper/apps/bot-discord/src/config.json
      - /data/revanced-helper/server-config.json:/usr/src/revanced-helper/apps/server/src/config.json
